### ISSUE TITLE
Problems encountered when training data 

### ISSUE THREAD

**Issue by frothmoon** [TimoStoff/event_cnn_minimal#17]
Hello!
Thank you for your outstanding work!

I successfully downloaded the HQF dataset and configured the environment you introduced.

But I encountered a problem when cloning the repo and submodules.
`fatal: The remote branch inference is not found in the upstream origin`
Then I manually downloaded the branch code and put it into the folder.

I want to retrain your network using the HQF dataset to replicate your work. I have converted all the rosbag data to h5 format.
Due to my stupidity, I did not understand what is contained in the data_file `/tmp/extracted_data/data_file.txt` in the `config.json` file.
Following the prompt, I filled in the location of the h5 format dataset here, but encountered an error.
```
~/event_cnn_minimal-master$ python train.py --config config/reconstruction.json 
Traceback (most recent call last):
  File "train.py", line 107, in <module>
    main(config)
  File "train.py", line 56, in main
    data_loader = config.init_obj('data_loader', module_data)
  File "/home/gp/event_cnn_minimal-master/parse_config.py", line 93, in init_obj
    return getattr(module, module_name)(*args, **module_args)
  File "/home/gp/event_cnn_minimal-master/data_loader/data_loaders.py", line 25, in __init__
    dataset = concatenate_datasets(data_file, SequenceDataset, sequence_kwargs)
  File "/home/gp/event_cnn_minimal-master/utils/data.py", line 38, in concatenate_datasets
    data_paths = pd.read_csv(data_file, header=None).values.flatten().tolist()
  File "/home/gp/anaconda3/envs/event_cnn/lib/python3.7/site-packages/pandas/io/parsers.py", line 605, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/gp/anaconda3/envs/event_cnn/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/gp/anaconda3/envs/event_cnn/lib/python3.7/site-packages/pandas/io/parsers.py", line 814, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/gp/anaconda3/envs/event_cnn/lib/python3.7/site-packages/pandas/io/parsers.py", line 1045, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/gp/anaconda3/envs/event_cnn/lib/python3.7/site-packages/pandas/io/parsers.py", line 1893, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 518, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 717, in pandas._libs.parsers.TextReader._get_header
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
== Timing statistics ==
```
I should have filled in the wrong parameters.

Looking forward to your reply, thank you for your help.

**Comment by frothmoon** [comment]
@TimoStoff

**Comment by frothmoon** [comment]
The txt contains the directory of h5 files.

**Comment by HaoDot** [comment]
Hi @frothmoon [frothmoon](https://github.com/frothmoon)
Sorry to disturb u, could u provide the link of the h5 format of HQF? THX a lot. There are a few troubles when i converted the bag format files especially using the ros.
THX a lot!

**Comment by maqscui** [comment]
Hi @frothmoon can you tell me how you find **data._file.txt** file here to replace the path **/tmp/extracted_data/data_file.txt**
and what type of directories it contains.
