### ISSUE TITLE
Thank you for your outstanding work!

### ISSUE THREAD

**Issue by frothmoon** [TimoStoff/event_cnn_minimal#18]
Thank you for your outstanding work!

**Comment by frothmoon** [comment]
@TimoStoff @cedric-scheerlinck

**Comment by frothmoon** [comment]
I modified the 19th line in the `base/base_trainer.py` file, and the program did not continue to report errors.
`self.model = torch.nn.DataParallel(model, device_ids=device_ids).module`

But only one GPU is used.

`python train.py --config config/reconstruction.py --device 0,1 --batch_size 2`

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.67       Driver Version: 460.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  TITAN V             Off  | 00000000:1A:00.0 Off |                  N/A |
| 43%   61C    P2   105W / 250W |   6495MiB / 12066MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  TITAN V             Off  | 00000000:1B:00.0 Off |                  N/A |
| 29%   44C    P8    27W / 250W |      4MiB / 12066MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  TITAN V             Off  | 00000000:88:00.0 Off |                  N/A |
| 35%   47C    P0    39W / 250W |      0MiB / 12066MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  TITAN V             Off  | 00000000:89:00.0 Off |                  N/A |
| 28%   41C    P0    36W / 250W |      0MiB / 12066MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     10259      C   python                           6491MiB |
+-----------------------------------------------------------------------------+
```

**Comment by frothmoon** [comment]
> I modified the 19th line in the `base/base_trainer.py` file, and the program did not continue to report errors. `self.model = torch.nn.DataParallel(model, device_ids=device_ids).module`
> 
> But only one GPU is used.
> 
> `python train.py --config config/reconstruction.py --device 0,1 --batch_size 2`
> 
> ```
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 460.67       Driver Version: 460.67       CUDA Version: 10.1     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  TITAN V             Off  | 00000000:1A:00.0 Off |                  N/A |
> | 43%   61C    P2   105W / 250W |   6495MiB / 12066MiB |    100%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
> |   1  TITAN V             Off  | 00000000:1B:00.0 Off |                  N/A |
> | 29%   44C    P8    27W / 250W |      4MiB / 12066MiB |      0%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
> |   2  TITAN V             Off  | 00000000:88:00.0 Off |                  N/A |
> | 35%   47C    P0    39W / 250W |      0MiB / 12066MiB |      0%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
> |   3  TITAN V             Off  | 00000000:89:00.0 Off |                  N/A |
> | 28%   41C    P0    36W / 250W |      0MiB / 12066MiB |      0%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                                  |
> |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
> |        ID   ID                                                   Usage      |
> |=============================================================================|
> |    0   N/A  N/A     10259      C   python                           6491MiB |
> +-----------------------------------------------------------------------------+
> ```

Whenever the program runs to the 10th epoch validation, an error will be reported.
```
Concatenating <class 'data_loader.dataset.SequenceDataset'> datasets
  0%|                                                    | 0/10 [00:00<?, ?it/s]sensor resolution = [180 240]
 10%|████▍                                       | 1/10 [00:00<00:05,  1.59it/s]sensor resolution = [180 240]
 20%|████████▊                                   | 2/10 [00:00<00:03,  2.15it/s]sensor resolution = [180 240]
 30%|█████████████▏                              | 3/10 [00:01<00:02,  3.01it/s]sensor resolution = [180 240]
 40%|█████████████████▌                          | 4/10 [00:01<00:01,  4.08it/s]sensor resolution = [180 240]
 50%|██████████████████████                      | 5/10 [00:01<00:01,  3.43it/s]sensor resolution = [180 240]
 60%|██████████████████████████▍                 | 6/10 [00:01<00:01,  3.40it/s]sensor resolution = [180 240]
 70%|██████████████████████████████▊             | 7/10 [00:02<00:00,  3.54it/s]sensor resolution = [180 240]
 80%|███████████████████████████████████▏        | 8/10 [00:02<00:00,  3.73it/s]sensor resolution = [180 240]
 90%|███████████████████████████████████████▌    | 9/10 [00:02<00:00,  4.14it/s]sensor resolution = [180 240]
100%|███████████████████████████████████████████| 10/10 [00:02<00:00,  3.62it/s]
Concatenating <class 'data_loader.dataset.SequenceDataset'> datasets
  0%|                                                     | 0/4 [00:00<?, ?it/s]sensor resolution = [180 240]
 25%|███████████▎                                 | 1/4 [00:00<00:00,  7.58it/s]sensor resolution = [180 240]
 50%|██████████████████████▌                      | 2/4 [00:00<00:00,  3.32it/s]sensor resolution = [180 240]
 75%|█████████████████████████████████▊           | 3/4 [00:00<00:00,  3.79it/s]sensor resolution = [180 240]
100%|█████████████████████████████████████████████| 4/4 [00:01<00:00,  3.67it/s]
Using None final activation
Using skip: <function skip_sum at 0x7f77c29f4950>
Using UpsampleConvLayer (slow, but no checkerboard artefacts)
Kernel size 5
Skip type sum
norm none
E2VIDRecurrent(
  (unetrecurrent): UNetRecurrent(
    (head): ConvLayer(
      (conv2d): Conv2d(5, 32, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    )
    (encoders): ModuleList(
      (0): RecurrentConvLayer(
        (conv): ConvLayer(
          (conv2d): Conv2d(32, 64, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2))
        )
        (recurrent_block): ConvLSTM(
          (Gates): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        )
      )
      (1): RecurrentConvLayer(
        (conv): ConvLayer(
          (conv2d): Conv2d(64, 128, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2))
        )
        (recurrent_block): ConvLSTM(
          (Gates): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        )
      )
      (2): RecurrentConvLayer(
        (conv): ConvLayer(
          (conv2d): Conv2d(128, 256, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2))
        )
        (recurrent_block): ConvLSTM(
          (Gates): Conv2d(512, 1024, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        )
      )
    )
    (resblocks): ModuleList(
      (0): ResidualBlock(
        (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      )
      (1): ResidualBlock(
        (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      )
    )
    (decoders): ModuleList(
      (0): UpsampleConvLayer(
        (conv2d): Conv2d(256, 128, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
      )
      (1): UpsampleConvLayer(
        (conv2d): Conv2d(128, 64, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
      )
      (2): UpsampleConvLayer(
        (conv2d): Conv2d(64, 32, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
      )
    )
    (pred): ConvLayer(
      (conv2d): Conv2d(32, 1, kernel_size=(1, 1), stride=(1, 1))
    )
  )
)
Trainable parameters: 10710401
Setting up Perceptual loss...
Loading model from: /storage3/xxx/event_cnn_minimal-master/PerceptualSimilarity/models/weights/v0.1/vgg.pth
...[net-lin [vgg]] initialized
...Done
/home/xxx/anaconda3/envs/event_cnn/lib/python3.7/site-packages/torch/nn/functional.py:2705: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn("Default grid_sample and affine_grid behavior has changed "
Train Epoch: 1 [0/137 (0%)] perc: 0.6772 temp: 0.8624 loss: 1.5396 loss: 1.5396
Making preview train_0
add_video needs package moviepy
add_video needs package moviepy

......

Train Epoch: 10 [136/137 (99%)] perc: 0.5174 temp: 0.0157 loss: 0.5332 loss: 0.5332
validation
Traceback (most recent call last):
  File "train.py", line 107, in <module>
    main(config)
  File "train.py", line 78, in main
    trainer.train()
  File "/storage3/xxx/event_cnn_minimal-master/base/base_trainer.py", line 78, in train
    result = self._train_epoch(epoch)
  File "/storage3/xxx/event_cnn_minimal-master/trainer/trainer.py", line 134, in _train_epoch
    val_log = self._valid_epoch(epoch)
  File "/storage3/xxx/event_cnn_minimal-master/trainer/trainer.py", line 154, in _valid_epoch
    losses = self.forward_sequence(sequence, all_losses=True)
  File "/storage3/xxx/event_cnn_minimal-master/trainer/trainer.py", line 59, in forward_sequence
    pred = self.model(events)
  File "/home/xxx/anaconda3/envs/event_cnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/storage3/xxx/event_cnn_minimal-master/model/model.py", line 193, in forward
    output_dict = self.unetrecurrent.forward(event_tensor)
  File "/storage3/xxx/event_cnn_minimal-master/model/unet.py", line 283, in forward
    x = self.head(x)
  File "/home/xxx/anaconda3/envs/event_cnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/storage3/xxx/event_cnn_minimal-master/model/submodules.py", line 26, in forward
    out = self.conv2d(x)
  File "/home/xxx/anaconda3/envs/event_cnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xxx/anaconda3/envs/event_cnn/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/xxx/anaconda3/envs/event_cnn/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size 32 5 5 5, expected input[1, 10, 160, 160] to have 5 channels, but got 10 channels instead
== Timing statistics ==
```

**Comment by frothmoon** [comment]
```
Train Epoch: 71 [0/151 (0%)] perc: 0.3167 temp: 0.0363 loss: 0.3530 loss: 0.3530
Making preview train_0
Traceback (most recent call last):
  File "train.py", line 107, in <module>
    main(config)
  File "train.py", line 78, in main
    trainer.train()
  File "/storage3/xxx/event_cnn_minimal-master/base/base_trainer.py", line 79, in train
    result = self._train_epoch(epoch)
  File "/storage3/xxx/event_cnn_minimal-master/trainer/trainer.py", line 125, in _train_epoch
    self.preview(sequence, epoch, tag_prefix=f'train_{batch_idx}')
  File "/storage3/xxx/event_cnn_minimal-master/trainer/trainer.py", line 235, in preview
    self.writer.writer.add_video(f'{tag_prefix}', video_tensor, global_step=epoch, fps=20)
  File "/home/xxx/anaconda3/envs/event_cnn/lib/python3.7/site-packages/tensorboardX/writer.py", line 852, in add_video
    summary = video(tag, vid_tensor, fps, dataformats=dataformats)
  File "/home/xxx/anaconda3/envs/event_cnn/lib/python3.7/site-packages/tensorboardX/summary.py", line 352, in video
    video = make_video(tensor, fps)
  File "/home/xxx/anaconda3/envs/event_cnn/lib/python3.7/site-packages/tensorboardX/summary.py", line 379, in make_video
    clip.write_gif(filename, verbose=False, logger=None)
  File "<decorator-gen-167>", line 2, in write_gif
  File "/home/xxx/anaconda3/envs/event_cnn/lib/python3.7/site-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-166>", line 2, in write_gif
  File "/home/xxx/anaconda3/envs/event_cnn/lib/python3.7/site-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/home/xxx/anaconda3/envs/event_cnn/lib/python3.7/site-packages/moviepy/video/VideoClip.py", line 434, in write_gif
    logger=logger)
  File "/home/xxx/anaconda3/envs/event_cnn/lib/python3.7/site-packages/moviepy/video/io/gif_writers.py", line 285, in write_gif_with_image_io
    writer.append_data(frame)
  File "/home/xxx/anaconda3/envs/event_cnn/lib/python3.7/site-packages/imageio/core/format.py", line 502, in append_data
    return self._append_data(im, total_meta)
  File "/home/xxx/anaconda3/envs/event_cnn/lib/python3.7/site-packages/imageio/plugins/pillowmulti.py", line 116, in _append_data
    self._writer.add_image(im, duration, dispose)
  File "/home/xxx/anaconda3/envs/event_cnn/lib/python3.7/site-packages/imageio/plugins/pillowmulti.py", line 172, in add_image
    self.write_image(im_pil, palette, rect, duration, dispose)
  File "/home/xxx/anaconda3/envs/event_cnn/lib/python3.7/site-packages/imageio/plugins/pillowmulti.py", line 223, in write_image
    fp.write(d)
OSError: [Errno 28] No space left on device
== Timing statistics ==
[4]+  已杀死               python train.py --config config/reconstruction.json --device 0,1 --resume checkpoint/models/reconstruction/1005_161943/checkpoint-epoch17.pth

```
The space of a GPU is not enough in the end.
